const athleteBase={alex:{force:60,agility:60,technique:60},rafa:{force:80,agility:55,technique:45},lia:{force:45,agility:55,technique:80},maya:{force:45,agility:70,technique:65},leo:{force:60,agility:75,technique:45},nina:{force:45,agility:80,technique:55},caio:{force:75,agility:60,technique:45},iris:{force:35,agility:60,technique:85}};
const attributeLabels={force:'Força',agility:'Agilidade',technique:'Técnica'};
let athleteProgress={},matchAttributes=null,training=null,touchMoveTarget=null;
try{const saved=JSON.parse(localStorage.getItem('rebate-athlete-progress-v1')||'{}');for(const id of Object.keys(athleteBase)){athleteProgress[id]={};for(const key of Object.keys(attributeLabels)){const p=saved[id]?.[key];athleteProgress[id][key]={gain:Math.max(0,Math.min(15,Number.isInteger(p?.gain)?p.gain:0)),xp:Math.max(0,Math.min(39,Number.isInteger(p?.xp)?p.xp:0))};}}}catch{}
function athleteValues(id,trained=true){const base=athleteBase[id]||athleteBase.alex;return Object.fromEntries(Object.entries(base).map(([key,value])=>[key,Math.min(100,value+(trained?(athleteProgress[id]?.[key]?.gain||0):0))]));}
function resetAthleteMatch(){matchAttributes={player:athleteValues(playerCharacter),opponent:athleteValues(opponentCharacter,false)};training={force:0,agility:0,technique:0,paid:false};touchMoveTarget=null;renderAthleteBars();}
function athleteFactor(side,key){const value=matchAttributes?.[side]?.[key]??60;return key==='agility'?.85+.3*value/100:.8+.4*value/100;}
function athleteTolerance(side){return .065+.02*(matchAttributes?.[side]?.technique??60)/100;}
function attributeShot(own,isServe){if(isServe)return;const side=own?'player':'opponent';ball.speed=(ball.speed||1)*athleteFactor(side,'force');if(!ball.power)ball.curve=Math.max(-1,Math.min(1,(ball.curve||0)*athleteFactor(side,'technique')));}
function advancePlayerMovement(dt){if(held.has(hitKey()))return;const move=(held.has('arrowright')||held.has('d')?1:0)-(held.has('arrowleft')||held.has('a')?1:0),speed=7*athleteFactor('player','agility');if(move){touchMoveTarget=null;chooseLane(player+move*speed*dt);}else if(touchMoveTarget!==null){const delta=touchMoveTarget-player;chooseLane(player+Math.sign(delta)*Math.min(Math.abs(delta),speed*dt));if(Math.abs(player-touchMoveTarget)<.001)touchMoveTarget=null;}}
function trainReturn(curve,incoming){if(!training||training.paid)return;training.force=Math.min(10,training.force+1);if(Math.abs((incoming?.from??.5)-(incoming?.to??.5))>.3)training.agility=Math.min(10,training.agility+2);if(curve||matchStats.currentSequence>=3)training.technique=Math.min(10,training.technique+1);}
function finishAthleteTraining(){if(!training||training.paid)return;training.paid=true;const progress=athleteProgress[playerCharacter]||(athleteProgress[playerCharacter]={}),box=document.getElementById('athlete-training');box.replaceChildren();const title=document.createElement('strong');title.textContent='Evolução · '+characters.find(c=>c.id===playerCharacter).name;box.append(title);
 for(const key of Object.keys(attributeLabels)){const p=progress[key]||(progress[key]={gain:0,xp:0}),before=athleteValues(playerCharacter)[key],earned=p.gain>=15?0:training[key];p.xp+=earned;while(p.xp>=40&&p.gain<15){p.xp-=40;p.gain++;}if(p.gain>=15)p.xp=0;const after=athleteValues(playerCharacter)[key],row=document.createElement('p');row.textContent=attributeLabels[key]+': '+before+' → '+after+' · '+(p.gain>=15?'Treino máximo':('+'+earned+' XP · '+p.xp+'/40 para subir'));box.append(row);}
 try{localStorage.setItem('rebate-athlete-progress-v1',JSON.stringify(athleteProgress));}catch{}box.hidden=false;
}
function renderAthleteBars(){for(const [id,side] of [['athlete-upper',viewTop()?'player':'opponent'],['athlete-lower',viewTop()?'opponent':'player']]){const box=document.getElementById(id);box.hidden=!matchAttributes||state==='ready';if(box.hidden)continue;box.replaceChildren();const title=document.createElement('strong');title.textContent=(side==='player'?'Você':'Adversário')+' · '+characters.find(c=>c.id===(side==='player'?playerCharacter:opponentCharacter)).name;box.append(title);for(const [key,label] of Object.entries(attributeLabels)){const row=document.createElement('label'),bar=document.createElement('progress'),value=matchAttributes[side][key];bar.max=100;bar.value=value;row.textContent=label+' '+value+'/100';bar.setAttribute('aria-label',label+' '+value+' de 100');row.append(bar);box.append(row);}}}
