const musicalNotes=['Dó','Ré','Mi','Fá','Sol','Lá','Si','Dó↑','Ré↑'];
const arenaMelodies=[{name:'Salto da quadra',notes:[0,2,4,2]},{name:'Passo da torcida',notes:[1,3,5,4,1]},{name:'Volta da vitória',notes:[4,6,7,8,7,4]}];
let musicalEnabled=false,musicalHistory=[],musicalPending=null,musicalUsed=false,musicalDance=null;
function resetMusicalMatch(){musicalEnabled=playStyle==='arena'&&document.getElementById('arena-musical').checked;musicalHistory=[];musicalPending=null;musicalUsed=false;musicalDance=null;renderMusical();}
function resetMusicalRally(){musicalHistory=[];musicalPending=null;renderMusical();}
function musicalBounce(x,countsForMelody=false){if(!musicalEnabled||musicalDance||x<0||x>1)return;const note=Math.min(8,Math.floor(x*9));gameAudio.note?.(note);if(!countsForMelody)return;musicalHistory.push(note);musicalHistory=musicalHistory.slice(-6);if(!musicalUsed&&!musicalPending)musicalPending=arenaMelodies.find(m=>m.notes.length<=musicalHistory.length&&m.notes.every((n,i)=>n===musicalHistory[musicalHistory.length-m.notes.length+i]))||null;renderMusical();}
function renderMusical(){const box=document.getElementById('musical-status');box.hidden=!musicalEnabled;document.getElementById('musical-notes').textContent=musicalHistory.map(n=>musicalNotes[n]).join(' · ')||'Suas devoluções: Dó, Ré, Mi, Fá, Sol, Lá, Si, Dó↑, Ré↑';document.getElementById('musical-message').textContent=musicalDance?'Dança conjunta · '+Math.max(0,5-musicalDance.elapsed).toFixed(1)+'s':musicalPending?musicalPending.name+' descoberta! Dança depois do ponto.':musicalUsed?'Dança desta partida já realizada.':'Sua sequência: devolva nos destinos indicados na mesma troca. Saques não contam.';document.getElementById('musical-skip').hidden=!musicalDance;document.getElementById('musical-skip').disabled=state!=='playing';}
function beginMusicalDance(){if(!musicalEnabled||!musicalPending||musicalUsed)return false;musicalUsed=true;musicalDance={song:musicalPending,elapsed:0};renderArena();held.clear();touchMoveTarget=null;swing=0;gameAudio.stop();gameAudio.music?.(musicalDance.song.notes,0);renderMusical();return true;}
function finishMusicalDance(){if(!musicalDance||state!=='playing')return;musicalDance=null;musicalPending=null;held.clear();gameAudio.stop();renderMusical();finishPointTransition();}
function advanceMusicalDance(dt){musicalDance.elapsed+=dt;if(musicalDance.elapsed>=5)finishMusicalDance();else renderMusical();}
function resumeMusicalAudio(){if(musicalDance)gameAudio.music?.(musicalDance.song.notes,musicalDance.elapsed);}
document.getElementById('musical-skip').addEventListener('click',finishMusicalDance);
